name: FormatCheck
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  runic:
    name: "Runic"
    uses: "SciML/.github/.github/workflows/runic.yml@v1"
    secrets: "inherit"
